#define XY_VSFILTER_VERSION_MAJOR 3
#define XY_VSFILTER_VERSION_MINOR  0
#define XY_VSFILTER_VERSION_PATCH  0
#define XY_VSFILTER_VERSION_COMMIT 209
#define XY_VSFILTER_VERSION_COMMIT_SHA1 ""

#ifdef XY_SUB_FILTER_DLL
#define LIBASS_VERSION_STRING "0.17.0"
#define BUILD_DATE_STRING "2022/12/08"
#endif
